# Generated by Django 4.2.6 on 2024-02-15 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtaskmanager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auser',
        ),
    ]
