# Generated by Django 4.2.6 on 2024-02-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_task_user'),
        ('authtaskmanager', '0002_delete_auser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='taskmanager.task'),
        ),
    ]
